export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERR = 'ADD_PRODUCT_ERR';

export const START_PRODUCTS_DOWNLOAD = 'START_PRODUCTS_DOWNLOAD';
export const SUCCESS_PRODUCTS_DOWNLOAD = 'SUCCESS_PRODUCT_DOWNLOAD';
export const FAILED_PRODUCTS_DOWNLOAD = 'FAILED_PRODUCTS_DOWNLOAD';

export const GET_DELETE_PRODUCT = 'GET_DELETE_PRODUCT';
export const SUCCESS_PRODUCT_DELETE = 'SUCCESS_PRODUCT_DELETE';
export const FAILED_PRODUCT_DELETE = 'FAILED_PRODUCT_DELETE';

export const GET_EDIT_PRODUCT = 'GET_EDIT_PRODUCT';
export const START_EDIT_PRODUCT = 'START_PRODUCT_EDIT';
export const SUCCESS_PRODUCT_EDIT = 'SUCCESS_PRODUCT_EDIT';
export const FAILED_PRODUCT_EDIT = 'FAILED_PRODUCT_EDIT';
